---
title: "About"
---

- 👋 Hi, I’m @rocarvaj
- 🐦 [@rocarvaj](https://twitter.com/rocarvaj)
- 🦋 [@rocarvaj.bsky.social](https://bsky.app/profile/rocarvaj.bsky.social)
- 🐘 [@rocarvaj@mas.to](https://mas.to/@rocarvaj)
- 📫 rodolfo DOT lajavrac (in reverse order) AT uai DOT cl

### Who? ###
I'm a Teaching Associate Professor at the School of Business at [Universidad Adolfo Iba&ntilde;ez](http://www.uai.cl/facultades-y-carreras/escuela-de-negocios). I have a MS in Operations Research from [ISyE - GATech](http://www.isye.gatech.edu) and an 
I studied Mathematical Engineering (Applied Math) at [Universidad de Chile](http://www.dim.uchile.cl).

### Interests ###
Operations Research, Prescriptive Analytics, Mixed Integer Linear Programming (theory, applications and computational methodologies).

### Publications: ###
- [*Using diversification, communication and parallelism to solve mixed-integer linear programs.*](http://www.sciencedirect.com/science/article/pii/S0167637714000236) With S. Ahmed. G. Nemhauser, K. Furman,
V. Goel and Y. Shao. Operations Research Letters, 2014 `DOI:10.1016/j.orl.2013.12.012`.

- [*Imposing Connectivity Constraints in Forest Planning Models.*](https://pubsonline.informs.org/doi/10.1287/opre.2013.1183) With M. Constantino, M. Goycoolea, J. P. Vielma and A. Weintraub. Operations Research, 2013.
- [*Una experiencia en la ense&ntilde;anza de los primeros cursos del &aacute;rea matem&aacute;tica*][sochedi07]. With M. Matamala. XXI Congreso de Educaci&oacute;n en Ingenier&iacute;a SOCHEDI, 2007.
- [*Small Alliances in Graphs.*][mfcs07] [[pdf]][mfcs07_pdf] With M. Matamala, I. Rapaport and N. Schabanel. MFCS 2007, LNCS, pp. 218-227. Springer, Berlin. 2007.
- [*Comunidades en grafos.*][comunidades06] Engineering thesis. Advisor: I. Rapaport, co-advisor: M. Matamala, 2006.
- [*Bohemario*][bohemario95], poems, 1995.

### Technical reports ###
- [*Is more information better?*](https://dl.dropboxusercontent.com/u/356769/Research/isinformationbetter.pdf)

You can also check my [Google Scholar profile](http://scholar.google.com/citations?hl=en&user=O3DhVXMAAAAJ).

### Refereed for: ###
- [European Journal of Operational Research](http://www.journals.elsevier.com/european-journal-of-operational-research/).
- [Acta Mathematica Sinica](http://www.springer.com/mathematics/journal/10114).
- [Ars Combinatoria](http://www.combinatorialmath.ca/arscombinatoria/). 
- [LATIN](http://www.latintcs.org/)

### Collaborators and colleagues: ###
[Marcos Goycoolea](https://mgoycool.github.io/), 
[Andr&eacute;s Weintraub](http://www.dii.uchile.cl/~aweintra/), 
[Miguel Constantino](http://www.deio.fc.ul.pt/ficha_pessoal/ficha_miguel-constantino.php), 
[Juan Pablo Vielma](http://www.mit.edu/~jvielma/),
[Mart&iacute;n Matamala](http://www.dim.uchile.cl/~mmatamal),
[Iv&aacute;n Rapaport](http://www.dim.uchile.cl/~rapaport),
[Nicolas Schabanel](http://www.liafa.jussieu.fr/~nschaban/), 
[Gustavo Angulo](http://www2.isye.gatech.edu/~giao3), 
[Diego Mor&aacute;n](https://sites.google.com/view/damr), 
[Crist&oacute;bal Guzm&aacute;n](http://www2.isye.gatech.edu/~cguzman6/Home.html),
[Guido Lagos](http://www2.isye.gatech.edu/~grlb3/)
